from barks_fantagraphics.comics_consts import PageType

DEST_JPG_QUALITY = 95
DEST_JPG_COMPRESS_LEVEL = 9
MIN_HD_SRCE_HEIGHT = 3000

DEST_SRCE_MAP_FILENAME = "srce-dest-map.json"
DEST_PANELS_BBOXES_FILENAME = "dest-panels-bboxes.json"

PANELS_BBOX_HEIGHT_SIMILARITY_MARGIN = 100
README_FILENAME = "readme.txt"
SUMMARY_FILENAME = "clean_summary.txt"
METADATA_FILENAME = "metadata.txt"
JSON_METADATA_FILENAME = "comic-metadata.json"
DOUBLE_PAGES_SECTION = "double_pages"
PAGE_NUMBERS_SECTION = "page_numbers"
DOUBLE_PAGES = [PageType.BODY, PageType.BACK_NO_PANELS_DOUBLE, PageType.BLANK_PAGE]
DEST_NON_IMAGE_FILES = {
    SUMMARY_FILENAME,
    JSON_METADATA_FILENAME,
    DEST_PANELS_BBOXES_FILENAME,
    METADATA_FILENAME,
    README_FILENAME,
    DEST_SRCE_MAP_FILENAME,
}

FOOTNOTE_CHAR = "*"

DEST_TARGET_WIDTH = 2120
DEST_TARGET_HEIGHT = 3200
DEST_TARGET_X_MARGIN = 100
DEST_TARGET_ASPECT_RATIO = float(DEST_TARGET_HEIGHT) / float(DEST_TARGET_WIDTH)
