set -e

cd Configs

ln -s "A Financial Fable.ini" "WDCS 126.ini"
ln -s "Biceps Blues.ini" "WDCS 69.ini"
ln -s "Billions to Sneeze At.ini" "WDCS 124.ini"
ln -s "Donald Duck's Worst Nightmare.ini" "WDCS 101.ini"
ln -s "Donald Mines His Own Business.ini" "WDCS 81.ini"
ln -s "Donald of the Coast Guard.ini" "WDCS 94.ini"
ln -s "Donald's Love Letters.ini" "WDCS 111.ini"
ln -s "Donald's Posy Patch.ini" "WDCS 80.ini"
ln -s "Dowsing Ducks.ini" "WDCS 109.ini"
ln -s "Fireman Donald.ini" "WDCS 86.ini"
ln -s "Foxy Relations.ini" "WDCS 98.ini"
ln -s "Gemstone Hunters.ini" "WDCS 143.ini"
ln -s "Gladstone Returns.ini" "WDCS 95.ini"
ln -s "Gladstone's Luck.ini" "WDCS 131.ini"
ln -s "Gladstone's Terrible Secret.ini" "WDCS 140.ini"
ln -s "Gladstone's Usual Very Good Year.ini" "WDCS 136.ini"
ln -s "Going Ape.ini" "WDCS 91.ini"
ln -s "Going Buggy.ini" "WDCS 77.ini"
ln -s "Houseboat Holiday.ini" "WDCS 142.ini"
ln -s "Jam Robbers.ini" "WDCS 78.ini"
ln -s "Knightly Rivals.ini" "WDCS 128.ini"
ln -s "Links Hijinks.ini" "WDCS 96.ini"
ln -s "Magical Misery.ini" "WDCS 82.ini"
ln -s "Managing the Echo System.ini" "WDCS 105.ini"
ln -s "Operation St. Bernard.ini" "WDCS 125.ini"
ln -s "Pearls of Wisdom.ini" "WDCS 97.ini"
ln -s "Picnic Tricks.ini" "WDCS 79.ini"
ln -s "Pizen Spring Dude Ranch.ini" "WDCS 102.ini"
ln -s "Playin' Hookey.ini" "WDCS 72.ini"
ln -s "Plenty of Pets.ini" "WDCS 106.ini"
ln -s "Pool Sharks.ini" "WDCS 129.ini"
ln -s "Rip Van Donald.ini" "WDCS 112.ini"
ln -s "Rival Beachcombers.ini" "WDCS 103.ini"
ln -s "Rocket Race to the Moon.ini" "WDCS 93.ini"
ln -s "Rocket Wing Saves the Day.ini" "WDCS 139.ini"
ln -s "Serum to Codfish Cove.ini" "WDCS 114.ini"
ln -s "Spending Money.ini" "WDCS 144.ini"
ln -s "Spoil the Rod.ini" "WDCS 92.ini"
ln -s "Statuesque Spendthrifts.ini" "WDCS 138.ini"
ln -s "Super Snooper.ini" "WDCS 107.ini"
ln -s "Swimming Swindlers.ini" "WDCS 71.ini"
ln -s "Ten-Star Generals.ini" "WDCS 132.ini"
ln -s "Terror of the Beagle Boys.ini" "WDCS 134.ini"
ln -s "The April Foolers.ini" "WDCS 127.ini"
ln -s "The Big Bin on Killmotor Hill.ini" "WDCS 135.ini"
ln -s "The Bill Collectors.ini" "WDCS 74.ini"
ln -s "The Cantankerous Cat.ini" "WDCS 76.ini"
ln -s "The Crazy Quiz Show.ini" "WDCS 99.ini"
ln -s "The Easter Election.ini" "WDCS 151.ini"
ln -s "The Gold-Finder.ini" "WDCS 73.ini"
ln -s "The Goldilocks Gambit.ini" "WDCS 110.ini"
ln -s "The Great Duckburg Frog-Jumping Contest.ini" "WDCS 108.ini"
ln -s "The Masters of Melody.ini" "WDCS 85.ini"
ln -s "The Screaming Cowboy.ini" "WDCS 137.ini"
ln -s "The Smugsnorkle Squattie.ini" "WDCS 70.ini"
ln -s "The Sunken Yacht.ini" "WDCS 104.ini"
ln -s "The Terrible Turkey.ini" "WDCS 87.ini"
ln -s "The Think Box Bollix.ini" "WDCS 141.ini"
ln -s "The Trouble With Dimes.ini" "WDCS 130.ini"
ln -s "The Truant Nephews.ini" "WDCS 133.ini"
ln -s "The Waltz King.ini" "WDCS 84.ini"
ln -s "Truant Officer Donald.ini" "WDCS 100.ini"
ln -s "Turkey Raffle.ini" "WDCS 75.ini"
ln -s "Vacation Misery.ini" "WDCS 83.ini"
ln -s "Watching the Watchman.ini" "WDCS 89.ini"
ln -s "Wild about Flowers.ini" "WDCS 117.ini"
ln -s "Wintertime Wager.ini" "WDCS 88.ini"
ln -s "Wired.ini" "WDCS 90.ini"
