from collections import defaultdict
from enum import Enum
from typing import Dict, List

from .barks_titles import Titles


class Tags(Enum):
    ALGERIA = "Algeria"
    ANDES = "Andes"
    ARABIAN_PENINSULA = "Arabian Peninsula"
    AUSTRALIA = "Australia"
    CENTRAL_AFRICA = "Central Africa"
    CHINA = "China"
    CONGO = "Congo"
    DUCKBURG = "Duckburg"
    EGYPT = "Egypt"
    FRANCE = "France"
    GERMANY = "Germany"
    GREECE = "Greece"
    HIMALAYAS = "Himalayas"
    INDIA = "India"
    INDIAN_OCEAN = "Indian Ocean"
    INDO_CHINA = "Indo-China"
    IRAQ = "Iraq"
    ITALY = "Italy"
    LIBYA = "Libya"
    MALI = "Mali"
    MONGOLIA = "Mongolia"
    MOROCCO = "Morocco"
    NIAGARA_FALLS = "Niagara Falls"
    NORWAY = "Norway"
    PAKISTAN = "Pakistan"
    PERSIA = "Persia"
    PLAIN_AWFUL = "Plain Awful"
    RUSSIA = "Russia"
    SCOTLAND = "Scotland"
    SOUTH_AFRICA = "South Africa"
    SPAIN = "Spain"
    SUDAN = "Sudan"
    SWEDEN = "Sweden"
    SWITZERLAND = "Switzerland"
    SYDNEY = "Sydney"
    SYRIA = "Syria"
    TANGANYIKA = "Tanganyika"

    AIRPLANE = "airplane"
    FIRE = "fire"
    SQUARE_EGGS = "square eggs"

    ARGUS_MCFIENDY = "Argus McFiendy"
    BEAGLE_BOYS = "The Beagle Boys"
    FLINTHEART_GLOMGOLD = "Flintheart Glomgold"
    GENERAL_SNOZZIE = "General Snozzie"
    GLADSTONE_GANDER = "Gladstone Gander"
    GYRO_GEARLOOSE = "Gyro Gearloose"
    HERBERT = "Herbert"
    MAGICA_DE_SPELL = "Magica de Spell"
    NEIGHBOR_JONES = "Neighbor Jones"


BARKS_TAG_ALIASES = {
    "algeria": Tags.ALGERIA,
    "andes": Tags.ANDES,
    "arabian peninsula": Tags.ARABIAN_PENINSULA,
    "arabia": Tags.ARABIAN_PENINSULA,
    "australia": Tags.AUSTRALIA,
    "central africa": Tags.CENTRAL_AFRICA,
    "china": Tags.CHINA,
    "congo": Tags.CONGO,
    "duckburg": Tags.DUCKBURG,
    "egypt": Tags.EGYPT,
    "france": Tags.FRANCE,
    "germany": Tags.GERMANY,
    "greece": Tags.GREECE,
    "himalayas": Tags.HIMALAYAS,
    "india": Tags.INDIA,
    "indian ocean": Tags.INDIAN_OCEAN,
    "indo-china": Tags.INDO_CHINA,
    "iraq": Tags.IRAQ,
    "italy": Tags.ITALY,
    "libya": Tags.LIBYA,
    "mali": Tags.MALI,
    "mongolia": Tags.MONGOLIA,
    "morocco": Tags.MOROCCO,
    "niagara falls": Tags.NIAGARA_FALLS,
    "niagara": Tags.NIAGARA_FALLS,
    "norway": Tags.NORWAY,
    "pakistan": Tags.PAKISTAN,
    "persia": Tags.PERSIA,
    "plain awful": Tags.PLAIN_AWFUL,
    "russia": Tags.RUSSIA,
    "scotland": Tags.SCOTLAND,
    "south africa": Tags.SOUTH_AFRICA,
    "spain": Tags.SPAIN,
    "sudan": Tags.SUDAN,
    "sweden": Tags.SWEDEN,
    "switzerland": Tags.SWITZERLAND,
    "sydney": Tags.SYDNEY,
    "syria": Tags.SYRIA,
    "tanganyika": Tags.TANGANYIKA,
    "airplane": Tags.AIRPLANE,
    "aeroplane": Tags.AIRPLANE,
    "fire": Tags.FIRE,
    "square eggs": Tags.SQUARE_EGGS,
    "argus mcfiendy": Tags.ARGUS_MCFIENDY,
    "argus": Tags.ARGUS_MCFIENDY,
    "mcfiendy": Tags.ARGUS_MCFIENDY,
    "beagle boys": Tags.BEAGLE_BOYS,
    "the beagle boys": Tags.BEAGLE_BOYS,
    "beagles": Tags.BEAGLE_BOYS,
    "flintheart glomgold": Tags.FLINTHEART_GLOMGOLD,
    "flintheart": Tags.FLINTHEART_GLOMGOLD,
    "glomgold": Tags.FLINTHEART_GLOMGOLD,
    "general snozzie": Tags.GENERAL_SNOZZIE,
    "snozzie": Tags.GENERAL_SNOZZIE,
    "gladstone gander": Tags.GLADSTONE_GANDER,
    "gladstone": Tags.GLADSTONE_GANDER,
    "gyro gearloose": Tags.GYRO_GEARLOOSE,
    "gyro": Tags.GYRO_GEARLOOSE,
    "gearloose": Tags.GYRO_GEARLOOSE,
    "herbert": Tags.HERBERT,
    "magica de spell": Tags.MAGICA_DE_SPELL,
    "magica": Tags.MAGICA_DE_SPELL,
    "spell": Tags.MAGICA_DE_SPELL,
    "neighbor jones": Tags.NEIGHBOR_JONES,
    "jones": Tags.NEIGHBOR_JONES,
}


class TagCategories(Enum):
    CHARACTERS = "Characters"
    PLACES = "Places"
    THINGS = "Things"


class TagGroups(Enum):
    AFRICA = "Africa"
    ASIA = "Asia"
    AUSTRALIA = "Australia"
    EUROPE = "Europe"
    NORTH_AMERICA = "North America"
    OTHER = "Other"
    SOUTH_AMERICA = "South America"


BARKS_TAG_GROUPS_ALIASES = {
    "africa": TagGroups.AFRICA,
    "asia": TagGroups.ASIA,
    "australia": TagGroups.AUSTRALIA,
    "europe": TagGroups.EUROPE,
    "north america": TagGroups.NORTH_AMERICA,
    "other": TagGroups.OTHER,
    "south america": TagGroups.SOUTH_AMERICA,
}


BARKS_TAG_CATEGORIES_DICT = {cat.name: cat for cat in TagCategories}

BARKS_TAG_CATEGORIES = {
    TagCategories.THINGS: [
        Tags.AIRPLANE,
        Tags.FIRE,
        Tags.SQUARE_EGGS,
    ],
    TagCategories.CHARACTERS: [
        Tags.ARGUS_MCFIENDY,
        Tags.BEAGLE_BOYS,
        Tags.FLINTHEART_GLOMGOLD,
        Tags.GENERAL_SNOZZIE,
        Tags.GLADSTONE_GANDER,
        Tags.GYRO_GEARLOOSE,
        Tags.HERBERT,
        Tags.MAGICA_DE_SPELL,
        Tags.NEIGHBOR_JONES,
    ],
    TagCategories.PLACES: [
        TagGroups.AFRICA,
        Tags.ALGERIA,
        Tags.ANDES,
        Tags.ARABIAN_PENINSULA,
        TagGroups.ASIA,
        #Tags.AUSTRALIA,
        TagGroups.AUSTRALIA,
        Tags.CENTRAL_AFRICA,
        Tags.CHINA,
        Tags.CONGO,
        Tags.DUCKBURG,
        Tags.EGYPT,
        TagGroups.EUROPE,
        Tags.FRANCE,
        Tags.GERMANY,
        Tags.GREECE,
        Tags.HIMALAYAS,
        Tags.INDIA,
        Tags.INDIAN_OCEAN,
        Tags.INDO_CHINA,
        Tags.IRAQ,
        Tags.ITALY,
        Tags.LIBYA,
        Tags.MALI,
        Tags.MONGOLIA,
        Tags.MOROCCO,
        Tags.NIAGARA_FALLS,
        TagGroups.NORTH_AMERICA,
        Tags.NORWAY,
        Tags.PAKISTAN,
        Tags.PERSIA,
        Tags.PLAIN_AWFUL,
        Tags.RUSSIA,
        Tags.SCOTLAND,
        Tags.SOUTH_AFRICA,
        TagGroups.SOUTH_AMERICA,
        Tags.SPAIN,
        Tags.SUDAN,
        Tags.SWEDEN,
        Tags.SWITZERLAND,
        Tags.SYDNEY,
        Tags.SYRIA,
        Tags.TANGANYIKA,
    ],
}

BARKS_TAG_GROUPS = {
    TagGroups.AFRICA: [
        Tags.ALGERIA,
        Tags.ARABIAN_PENINSULA,
        Tags.CENTRAL_AFRICA,
        Tags.CONGO,
        Tags.EGYPT,
        Tags.LIBYA,
        Tags.MALI,
        Tags.MOROCCO,
        Tags.SOUTH_AFRICA,
        Tags.SUDAN,
        Tags.TANGANYIKA,
    ],
    TagGroups.ASIA: [
        Tags.CHINA,
        Tags.INDO_CHINA,
        Tags.HIMALAYAS,
        Tags.INDIA,
        Tags.IRAQ,
        Tags.MONGOLIA,
        Tags.PAKISTAN,
        Tags.PERSIA,
    ],
    TagGroups.AUSTRALIA: [
        Tags.AUSTRALIA,
        Tags.SYDNEY,
    ],
    TagGroups.EUROPE: [
        Tags.SWITZERLAND,
        Tags.SWEDEN,
        Tags.ITALY,
        Tags.FRANCE,
        Tags.GERMANY,
        Tags.SCOTLAND,
        Tags.SPAIN,
        Tags.RUSSIA,
        Tags.GREECE,
        Tags.NORWAY,
    ],
    TagGroups.NORTH_AMERICA: [],
    TagGroups.OTHER: [
        Tags.DUCKBURG,
    ],
    TagGroups.SOUTH_AMERICA: [
        Tags.ANDES,
        Tags.PLAIN_AWFUL,
    ],
}

BARKS_TAGGED_TITLES = defaultdict(list)

BARKS_TAGGED_TITLES[Tags.ALGERIA].append((Titles.ROCKET_RACE_AROUND_THE_WORLD, []))
BARKS_TAGGED_TITLES[Tags.ANDES].append((Titles.LOST_IN_THE_ANDES, []))
BARKS_TAGGED_TITLES[Tags.ARABIAN_PENINSULA].append((Titles.MINES_OF_KING_SOLOMON_THE, []))
BARKS_TAGGED_TITLES[Tags.ARABIAN_PENINSULA].append((Titles.MONEY_CHAMP_THE, []))
BARKS_TAGGED_TITLES[Tags.ARABIAN_PENINSULA].append((Titles.PIPELINE_TO_DANGER, []))
BARKS_TAGGED_TITLES[Tags.ARABIAN_PENINSULA].append((Titles.CAVE_OF_ALI_BABA, []))
BARKS_TAGGED_TITLES[Tags.ARABIAN_PENINSULA].append((Titles.MCDUCK_OF_ARABIA, []))
BARKS_TAGGED_TITLES[Tags.AUSTRALIA].append((Titles.ADVENTURE_DOWN_UNDER, []))
BARKS_TAGGED_TITLES[Tags.AUSTRALIA].append((Titles.RICHES_RICHES_EVERYWHERE, []))
BARKS_TAGGED_TITLES[Tags.AUSTRALIA].append((Titles.QUEEN_OF_THE_WILD_DOG_PACK_THE, []))
BARKS_TAGGED_TITLES[Tags.CENTRAL_AFRICA].append((Titles.DARKEST_AFRICA, []))
BARKS_TAGGED_TITLES[Tags.CENTRAL_AFRICA].append((Titles.VOODOO_HOODOO, []))
BARKS_TAGGED_TITLES[Tags.CENTRAL_AFRICA].append((Titles.JUNGLE_HI_JINKS, []))
BARKS_TAGGED_TITLES[Tags.CENTRAL_AFRICA].append((Titles.WISHING_WELL_THE, []))
BARKS_TAGGED_TITLES[Tags.CENTRAL_AFRICA].append((Titles.JUNGLE_BUNGLE, []))
BARKS_TAGGED_TITLES[Tags.CENTRAL_AFRICA].append((Titles.SO_FAR_AND_NO_SAFARI, []))
BARKS_TAGGED_TITLES[Tags.CHINA].append((Titles.MONEY_CHAMP_THE, []))
BARKS_TAGGED_TITLES[Tags.CONGO].append((Titles.BONGO_ON_THE_CONGO, []))
BARKS_TAGGED_TITLES[Tags.EGYPT].append((Titles.DONALD_DUCK_AND_THE_MUMMYS_RING, []))
BARKS_TAGGED_TITLES[Tags.FRANCE].append((Titles.DANGEROUS_DISGUISE, []))
BARKS_TAGGED_TITLES[Tags.GERMANY].append((Titles.FABULOUS_PHILOSOPHERS_STONE_THE, []))
BARKS_TAGGED_TITLES[Tags.GREECE].append((Titles.FABULOUS_PHILOSOPHERS_STONE_THE, []))
BARKS_TAGGED_TITLES[Tags.GREECE].append((Titles.GOLDEN_FLEECING_THE, []))
BARKS_TAGGED_TITLES[Tags.GREECE].append((Titles.ODDBALL_ODYSSEY, []))
BARKS_TAGGED_TITLES[Tags.GREECE].append((Titles.INSTANT_HERCULES, []))
BARKS_TAGGED_TITLES[Tags.HIMALAYAS].append((Titles.TRAIL_OF_THE_UNICORN, []))
BARKS_TAGGED_TITLES[Tags.HIMALAYAS].append((Titles.TRALLA_LA, []))
BARKS_TAGGED_TITLES[Tags.HIMALAYAS].append((Titles.LOST_CROWN_OF_GENGHIS_KHAN_THE, []))
BARKS_TAGGED_TITLES[Tags.INDIA].append((Titles.MAHARAJAH_DONALD, []))
BARKS_TAGGED_TITLES[Tags.INDIA].append((Titles.TRAIL_OF_THE_UNICORN, []))
BARKS_TAGGED_TITLES[Tags.INDIA].append((Titles.MINES_OF_KING_SOLOMON_THE, []))
BARKS_TAGGED_TITLES[Tags.INDIA].append((Titles.BILLION_DOLLAR_SAFARI_THE, []))
BARKS_TAGGED_TITLES[Tags.INDIA].append((Titles.ROCKET_RACE_AROUND_THE_WORLD, []))
BARKS_TAGGED_TITLES[Tags.INDIAN_OCEAN].append((Titles.MANY_FACES_OF_MAGICA_DE_SPELL_THE, []))
BARKS_TAGGED_TITLES[Tags.INDIAN_OCEAN].append((Titles.DOOM_DIAMOND_THE, []))
BARKS_TAGGED_TITLES[Tags.INDO_CHINA].append((Titles.CITY_OF_GOLDEN_ROOFS, []))
BARKS_TAGGED_TITLES[Tags.INDO_CHINA].append((Titles.MCDUCK_OF_ARABIA, []))
BARKS_TAGGED_TITLES[Tags.INDO_CHINA].append((Titles.TREASURE_OF_MARCO_POLO, []))
BARKS_TAGGED_TITLES[Tags.INDO_CHINA].append((Titles.MONKEY_BUSINESS, []))
BARKS_TAGGED_TITLES[Tags.IRAQ].append((Titles.FABULOUS_PHILOSOPHERS_STONE_THE, []))
BARKS_TAGGED_TITLES[Tags.IRAQ].append((Titles.RUG_RIDERS_IN_THE_SKY, []))
BARKS_TAGGED_TITLES[Tags.ITALY].append((Titles.FABULOUS_PHILOSOPHERS_STONE_THE, []))
BARKS_TAGGED_TITLES[Tags.ITALY].append((Titles.MIDAS_TOUCH_THE, []))
BARKS_TAGGED_TITLES[Tags.ITALY].append((Titles.UNSAFE_SAFE_THE, []))
BARKS_TAGGED_TITLES[Tags.ITALY].append((Titles.ODDBALL_ODYSSEY, []))
BARKS_TAGGED_TITLES[Tags.ITALY].append((Titles.FOR_OLD_DIMES_SAKE, []))
BARKS_TAGGED_TITLES[Tags.ITALY].append((Titles.MANY_FACES_OF_MAGICA_DE_SPELL_THE, []))
BARKS_TAGGED_TITLES[Tags.ITALY].append((Titles.DUCKS_EYE_VIEW_OF_EUROPE_A, []))
BARKS_TAGGED_TITLES[Tags.LIBYA].append((Titles.ROCKET_RACE_AROUND_THE_WORLD, []))
BARKS_TAGGED_TITLES[Tags.MALI].append((Titles.DAY_DUCKBURG_GOT_DYED_THE, []))
BARKS_TAGGED_TITLES[Tags.MALI].append((Titles.CANDY_KID_THE, []))
BARKS_TAGGED_TITLES[Tags.MONGOLIA].append((Titles.MONEY_CHAMP_THE, []))
BARKS_TAGGED_TITLES[Tags.MOROCCO].append((Titles.MAGIC_HOURGLASS_THE, []))
BARKS_TAGGED_TITLES[Tags.NIAGARA_FALLS].append((Titles.HIGH_WIRE_DAREDEVILS, []))
BARKS_TAGGED_TITLES[Tags.NORWAY].append((Titles.LEMMING_WITH_THE_LOCKET_THE, []))
BARKS_TAGGED_TITLES[Tags.PAKISTAN].append((Titles.LOST_CROWN_OF_GENGHIS_KHAN_THE, []))
BARKS_TAGGED_TITLES[Tags.PERSIA].append((Titles.IN_ANCIENT_PERSIA, []))
BARKS_TAGGED_TITLES[Tags.PLAIN_AWFUL].append((Titles.LOST_IN_THE_ANDES, []))
BARKS_TAGGED_TITLES[Tags.RUSSIA].append((Titles.CITY_OF_GOLDEN_ROOFS, []))
BARKS_TAGGED_TITLES[Tags.SCOTLAND].append((Titles.OLD_CASTLES_SECRET_THE, []))
BARKS_TAGGED_TITLES[Tags.SCOTLAND].append((Titles.HOUND_OF_THE_WHISKERVILLES, []))
BARKS_TAGGED_TITLES[Tags.SCOTLAND].append((Titles.INVISIBLE_INTRUDER_THE, []))
BARKS_TAGGED_TITLES[Tags.SCOTLAND].append((Titles.MYSTERY_OF_THE_LOCH, []))
BARKS_TAGGED_TITLES[Tags.SOUTH_AFRICA].append((Titles.SECOND_RICHEST_DUCK_THE, []))
BARKS_TAGGED_TITLES[Tags.SOUTH_AFRICA].append((Titles.SO_FAR_AND_NO_SAFARI, []))
BARKS_TAGGED_TITLES[Tags.SPAIN].append((Titles.DANGEROUS_DISGUISE, []))
BARKS_TAGGED_TITLES[Tags.SPAIN].append((Titles.ROCKET_RACE_AROUND_THE_WORLD, []))
BARKS_TAGGED_TITLES[Tags.SUDAN].append((Titles.MINES_OF_KING_SOLOMON_THE, []))
BARKS_TAGGED_TITLES[Tags.SWEDEN].append((Titles.MINES_OF_KING_SOLOMON_THE, []))
BARKS_TAGGED_TITLES[Tags.SWITZERLAND].append((Titles.DUCKS_EYE_VIEW_OF_EUROPE_A, []))
BARKS_TAGGED_TITLES[Tags.SYDNEY].append((Titles.ADVENTURE_DOWN_UNDER, []))
BARKS_TAGGED_TITLES[Tags.SYRIA].append((Titles.FABULOUS_PHILOSOPHERS_STONE_THE, []))
BARKS_TAGGED_TITLES[Tags.TANGANYIKA].append((Titles.UNSAFE_SAFE_THE, []))

BARKS_TAGGED_TITLES[Tags.DUCKBURG].append((Titles.HIGH_WIRE_DAREDEVILS, []))
BARKS_TAGGED_TITLES[Tags.DUCKBURG].append((Titles.CHRISTMAS_IN_DUCKBURG, []))
BARKS_TAGGED_TITLES[Tags.DUCKBURG].append((Titles.TITANIC_ANTS_THE, []))
BARKS_TAGGED_TITLES[Tags.DUCKBURG].append((Titles.LAND_BENEATH_THE_GROUND, []))
BARKS_TAGGED_TITLES[Tags.DUCKBURG].append((Titles.HIS_HANDY_ANDY, []))
BARKS_TAGGED_TITLES[Tags.DUCKBURG].append((Titles.DUCKBURGS_DAY_OF_PERIL, []))
BARKS_TAGGED_TITLES[Tags.DUCKBURG].append((Titles.GIANT_ROBOT_ROBBERS_THE, []))
BARKS_TAGGED_TITLES[Tags.DUCKBURG].append((Titles.GREAT_DUCKBURG_FROG_JUMPING_CONTEST_THE, []))
BARKS_TAGGED_TITLES[Tags.DUCKBURG].append((Titles.OLYMPIC_HOPEFUL_THE, []))
BARKS_TAGGED_TITLES[Tags.DUCKBURG].append((Titles.DAY_DUCKBURG_GOT_DYED_THE, []))
BARKS_TAGGED_TITLES[Tags.DUCKBURG].append((Titles.CODE_OF_DUCKBURG_THE, []))
BARKS_TAGGED_TITLES[Tags.DUCKBURG].append((Titles.BLACK_WEDNESDAY, []))
BARKS_TAGGED_TITLES[Tags.DUCKBURG].append((Titles.DUCKBURG_PET_PARADE_THE, []))

BARKS_TAGGED_TITLES[Tags.AIRPLANE].append((Titles.TRUANT_NEPHEWS_THE, []))
BARKS_TAGGED_TITLES[Tags.AIRPLANE].append((Titles.MASTER_RAINMAKER_THE, []))
BARKS_TAGGED_TITLES[Tags.AIRPLANE].append((Titles.CROWN_OF_THE_MAYAS, []))
BARKS_TAGGED_TITLES[Tags.AIRPLANE].append((Titles.ADVENTURE_DOWN_UNDER, []))
BARKS_TAGGED_TITLES[Tags.AIRPLANE].append((Titles.NORTH_OF_THE_YUKON, []))
BARKS_TAGGED_TITLES[Tags.AIRPLANE].append((Titles.TRAIL_OF_THE_UNICORN, []))
BARKS_TAGGED_TITLES[Tags.AIRPLANE].append((Titles.TWO_WAY_LUCK, []))
BARKS_TAGGED_TITLES[Tags.AIRPLANE].append((Titles.GREAT_WIG_MYSTERY_THE, []))
BARKS_TAGGED_TITLES[Tags.AIRPLANE].append((Titles.BALLOONATICS, []))
BARKS_TAGGED_TITLES[Tags.AIRPLANE].append((Titles.FROZEN_GOLD, []))
BARKS_TAGGED_TITLES[Tags.AIRPLANE].append((Titles.LOST_FRONTIER, []))
BARKS_TAGGED_TITLES[Tags.AIRPLANE].append((Titles.FRAIDY_FALCON_THE, []))
BARKS_TAGGED_TITLES[Tags.AIRPLANE].append((Titles.TRALLA_LA, []))
BARKS_TAGGED_TITLES[Tags.AIRPLANE].append((Titles.SO_FAR_AND_NO_SAFARI, []))
BARKS_TAGGED_TITLES[Tags.AIRPLANE].append((Titles.VOLCANO_VALLEY, []))
BARKS_TAGGED_TITLES[Tags.AIRPLANE].append((Titles.VOODOO_HOODOO, []))
BARKS_TAGGED_TITLES[Tags.AIRPLANE].append((Titles.SPICY_TALE_A, []))
BARKS_TAGGED_TITLES[Tags.AIRPLANE].append((Titles.LAND_OF_THE_PYGMY_INDIANS, []))
BARKS_TAGGED_TITLES[Tags.AIRPLANE].append((Titles.GOOD_DEEDS_THE, []))
BARKS_TAGGED_TITLES[Tags.AIRPLANE].append((Titles.SECRET_OF_ATLANTIS_THE, []))
BARKS_TAGGED_TITLES[Tags.AIRPLANE].append((Titles.SMOKE_WRITER_IN_THE_SKY, []))
BARKS_TAGGED_TITLES[Tags.AIRPLANE].append((Titles.QUEEN_OF_THE_WILD_DOG_PACK_THE, []))

BARKS_TAGGED_TITLES[Tags.FIRE].append((Titles.FIREBUG_THE, []))
BARKS_TAGGED_TITLES[Tags.SQUARE_EGGS].append((Titles.LOST_IN_THE_ANDES, []))

BARKS_TAGGED_TITLES[Tags.ARGUS_MCFIENDY].append((Titles.DARKEST_AFRICA, []))

BARKS_TAGGED_TITLES[Tags.BEAGLE_BOYS].append((Titles.TERROR_OF_THE_BEAGLE_BOYS, []))
BARKS_TAGGED_TITLES[Tags.BEAGLE_BOYS].append((Titles.BIG_BIN_ON_KILLMOTOR_HILL_THE, []))
BARKS_TAGGED_TITLES[Tags.BEAGLE_BOYS].append((Titles.ONLY_A_POOR_OLD_MAN, []))
BARKS_TAGGED_TITLES[Tags.BEAGLE_BOYS].append((Titles.ROUND_MONEY_BIN_THE, []))
BARKS_TAGGED_TITLES[Tags.BEAGLE_BOYS].append((Titles.MENEHUNE_MYSTERY_THE, []))
BARKS_TAGGED_TITLES[Tags.BEAGLE_BOYS].append((Titles.SEVEN_CITIES_OF_CIBOLA_THE, []))
BARKS_TAGGED_TITLES[Tags.BEAGLE_BOYS].append((Titles.MYSTERIOUS_STONE_RAY_THE, []))
BARKS_TAGGED_TITLES[Tags.BEAGLE_BOYS].append((Titles.FANTASTIC_RIVER_RACE_THE, []))
BARKS_TAGGED_TITLES[Tags.BEAGLE_BOYS].append((Titles.MONEY_WELL_THE, []))
BARKS_TAGGED_TITLES[Tags.BEAGLE_BOYS].append((Titles.CHRISTMAS_IN_DUCKBURG, []))
BARKS_TAGGED_TITLES[Tags.BEAGLE_BOYS].append((Titles.STRANGE_SHIPWRECKS_THE, []))
BARKS_TAGGED_TITLES[Tags.BEAGLE_BOYS].append((Titles.TWENTY_FOUR_CARAT_MOON_THE, []))
BARKS_TAGGED_TITLES[Tags.BEAGLE_BOYS].append((Titles.PAUL_BUNYAN_MACHINE_THE, []))
BARKS_TAGGED_TITLES[Tags.BEAGLE_BOYS].append((Titles.ALL_AT_SEA, []))
BARKS_TAGGED_TITLES[Tags.BEAGLE_BOYS].append((Titles.TREE_TRICK, []))
BARKS_TAGGED_TITLES[Tags.BEAGLE_BOYS].append((Titles.BILLIONS_IN_THE_HOLE, []))
BARKS_TAGGED_TITLES[Tags.BEAGLE_BOYS].append((Titles.GIFT_LION, []))
BARKS_TAGGED_TITLES[Tags.BEAGLE_BOYS].append((Titles.DEEP_DOWN_DOINGS, []))
BARKS_TAGGED_TITLES[Tags.BEAGLE_BOYS].append((Titles.UNSAFE_SAFE_THE, []))
BARKS_TAGGED_TITLES[Tags.BEAGLE_BOYS].append((Titles.TRICKY_EXPERIMENT, []))
BARKS_TAGGED_TITLES[Tags.BEAGLE_BOYS].append((Titles.STATUS_SEEKER_THE, []))
BARKS_TAGGED_TITLES[Tags.BEAGLE_BOYS].append((Titles.CASE_OF_THE_STICKY_MONEY_THE, []))
BARKS_TAGGED_TITLES[Tags.BEAGLE_BOYS].append((Titles.ISLE_OF_GOLDEN_GEESE, []))
BARKS_TAGGED_TITLES[Tags.BEAGLE_BOYS].append((Titles.HOW_GREEN_WAS_MY_LETTUCE, []))
BARKS_TAGGED_TITLES[Tags.BEAGLE_BOYS].append((Titles.GIANT_ROBOT_ROBBERS_THE, []))
BARKS_TAGGED_TITLES[Tags.BEAGLE_BOYS].append((Titles.HOUSE_OF_HAUNTS, []))
BARKS_TAGGED_TITLES[Tags.BEAGLE_BOYS].append((Titles.HEEDLESS_HORSEMAN_THE, []))
BARKS_TAGGED_TITLES[Tags.BEAGLE_BOYS].append((Titles.DOOM_DIAMOND_THE, []))
BARKS_TAGGED_TITLES[Tags.BEAGLE_BOYS].append((Titles.MR_PRIVATE_EYE, []))
BARKS_TAGGED_TITLES[Tags.BEAGLE_BOYS].append((Titles.DELIVERY_DILEMMA, []))

BARKS_TAGGED_TITLES[Tags.FLINTHEART_GLOMGOLD].append((Titles.SECOND_RICHEST_DUCK_THE, []))
BARKS_TAGGED_TITLES[Tags.FLINTHEART_GLOMGOLD].append((Titles.MONEY_CHAMP_THE, []))
BARKS_TAGGED_TITLES[Tags.FLINTHEART_GLOMGOLD].append((Titles.SO_FAR_AND_NO_SAFARI, []))

BARKS_TAGGED_TITLES[Tags.GENERAL_SNOZZIE].append((Titles.PHANTOM_OF_NOTRE_DUCK_THE, []))
BARKS_TAGGED_TITLES[Tags.GENERAL_SNOZZIE].append((Titles.DODGING_MISS_DAISY, []))
BARKS_TAGGED_TITLES[Tags.GENERAL_SNOZZIE].append((Titles.BLACK_FOREST_RESCUE_THE, []))
BARKS_TAGGED_TITLES[Tags.GENERAL_SNOZZIE].append((Titles.HOUND_HOUNDER, []))
BARKS_TAGGED_TITLES[Tags.GENERAL_SNOZZIE].append((Titles.MEDALING_AROUND, []))
BARKS_TAGGED_TITLES[Tags.GENERAL_SNOZZIE].append((Titles.BEACH_BOY, []))
BARKS_TAGGED_TITLES[Tags.GENERAL_SNOZZIE].append((Titles.DUCK_OUT_OF_LUCK, []))

BARKS_TAGGED_TITLES[Tags.GLADSTONE_GANDER].append((Titles.YOU_CANT_GUESS, []))
BARKS_TAGGED_TITLES[Tags.GLADSTONE_GANDER].append((Titles.SECRET_OF_HONDORICA, []))
BARKS_TAGGED_TITLES[Tags.GLADSTONE_GANDER].append((Titles.RACE_TO_THE_SOUTH_SEAS, []))
BARKS_TAGGED_TITLES[Tags.GLADSTONE_GANDER].append((Titles.LUCK_OF_THE_NORTH, []))
BARKS_TAGGED_TITLES[Tags.GLADSTONE_GANDER].append((Titles.TRAIL_OF_THE_UNICORN, []))
BARKS_TAGGED_TITLES[Tags.GLADSTONE_GANDER].append((Titles.CHRISTMAS_FOR_SHACKTOWN_A, []))
BARKS_TAGGED_TITLES[Tags.GLADSTONE_GANDER].append((Titles.GILDED_MAN_THE, []))
BARKS_TAGGED_TITLES[Tags.GLADSTONE_GANDER].append((Titles.LOST_RABBIT_FOOT_THE, []))
BARKS_TAGGED_TITLES[Tags.GLADSTONE_GANDER].append((Titles.BEAR_TAMER_THE, []))
BARKS_TAGGED_TITLES[Tags.GLADSTONE_GANDER].append((Titles.GOING_TO_PIECES, []))
BARKS_TAGGED_TITLES[Tags.GLADSTONE_GANDER].append((Titles.KITTY_GO_ROUND, []))
BARKS_TAGGED_TITLES[Tags.GLADSTONE_GANDER].append((Titles.GOLDEN_NUGGET_BOAT_THE, []))
BARKS_TAGGED_TITLES[Tags.GLADSTONE_GANDER].append((Titles.SEEING_IS_BELIEVING, []))
BARKS_TAGGED_TITLES[Tags.GLADSTONE_GANDER].append((Titles.BILLION_DOLLAR_SAFARI_THE, []))
BARKS_TAGGED_TITLES[Tags.GLADSTONE_GANDER].append((Titles.WINTERTIME_WAGER, []))
BARKS_TAGGED_TITLES[Tags.GLADSTONE_GANDER].append((Titles.GLADSTONE_RETURNS, []))
BARKS_TAGGED_TITLES[Tags.GLADSTONE_GANDER].append((Titles.LINKS_HIJINKS, []))
BARKS_TAGGED_TITLES[Tags.GLADSTONE_GANDER].append((Titles.RIVAL_BEACHCOMBERS, []))
BARKS_TAGGED_TITLES[Tags.GLADSTONE_GANDER].append((Titles.GOLDILOCKS_GAMBIT_THE, []))
BARKS_TAGGED_TITLES[Tags.GLADSTONE_GANDER].append((Titles.DONALDS_LOVE_LETTERS, []))
BARKS_TAGGED_TITLES[Tags.GLADSTONE_GANDER].append((Titles.WILD_ABOUT_FLOWERS, []))
BARKS_TAGGED_TITLES[Tags.GLADSTONE_GANDER].append((Titles.FINANCIAL_FABLE_A, []))
BARKS_TAGGED_TITLES[Tags.GLADSTONE_GANDER].append((Titles.KNIGHTLY_RIVALS, []))
BARKS_TAGGED_TITLES[Tags.GLADSTONE_GANDER].append((Titles.GLADSTONES_LUCK, []))
BARKS_TAGGED_TITLES[Tags.GLADSTONE_GANDER].append((Titles.GLADSTONES_USUAL_VERY_GOOD_YEAR, []))
BARKS_TAGGED_TITLES[Tags.GLADSTONE_GANDER].append((Titles.GLADSTONES_TERRIBLE_SECRET, []))
BARKS_TAGGED_TITLES[Tags.GLADSTONE_GANDER].append((Titles.GEMSTONE_HUNTERS, []))
BARKS_TAGGED_TITLES[Tags.GLADSTONE_GANDER].append((Titles.CHARITABLE_CHORE_A, []))
BARKS_TAGGED_TITLES[Tags.GLADSTONE_GANDER].append((Titles.MY_LUCKY_VALENTINE, []))
BARKS_TAGGED_TITLES[Tags.GLADSTONE_GANDER].append((Titles.EASTER_ELECTION_THE, []))
BARKS_TAGGED_TITLES[Tags.GLADSTONE_GANDER].append((Titles.SOME_HEIR_OVER_THE_RAINBOW, []))
BARKS_TAGGED_TITLES[Tags.GLADSTONE_GANDER].append((Titles.MASTER_RAINMAKER_THE, []))
BARKS_TAGGED_TITLES[Tags.GLADSTONE_GANDER].append((Titles.RAFFLE_REVERSAL, []))
BARKS_TAGGED_TITLES[Tags.GLADSTONE_GANDER].append((Titles.SALMON_DERBY, []))
BARKS_TAGGED_TITLES[Tags.GLADSTONE_GANDER].append((Titles.DAFFY_TAFFY_PULL_THE, []))
BARKS_TAGGED_TITLES[Tags.GLADSTONE_GANDER].append((Titles.GOOD_CANOES_AND_BAD_CANOES, []))
BARKS_TAGGED_TITLES[Tags.GLADSTONE_GANDER].append((Titles.SEARCHING_FOR_A_SUCCESSOR, []))
BARKS_TAGGED_TITLES[Tags.GLADSTONE_GANDER].append((Titles.RED_APPLE_SAP, []))
BARKS_TAGGED_TITLES[Tags.GLADSTONE_GANDER].append((Titles.TENDERFOOT_TRAP_THE, []))
BARKS_TAGGED_TITLES[Tags.GLADSTONE_GANDER].append((Titles.CODE_OF_DUCKBURG_THE, []))
BARKS_TAGGED_TITLES[Tags.GLADSTONE_GANDER].append((Titles.ROCKET_RACE_AROUND_THE_WORLD, []))
BARKS_TAGGED_TITLES[Tags.GLADSTONE_GANDER].append((Titles.MOCKING_BIRD_RIDGE, []))
BARKS_TAGGED_TITLES[Tags.GLADSTONE_GANDER].append((Titles.DRAMATIC_DONALD, []))
BARKS_TAGGED_TITLES[Tags.GLADSTONE_GANDER].append((Titles.BEACHCOMBERS_PICNIC_THE, []))
BARKS_TAGGED_TITLES[Tags.GLADSTONE_GANDER].append((Titles.LOVELORN_FIREMAN_THE, []))
BARKS_TAGGED_TITLES[Tags.GLADSTONE_GANDER].append((Titles.TURKEY_TROUBLE, []))
BARKS_TAGGED_TITLES[Tags.GLADSTONE_GANDER].append((Titles.DUCK_LUCK, []))
BARKS_TAGGED_TITLES[Tags.GLADSTONE_GANDER].append((Titles.JINXED_JALOPY_RACE_THE, []))
BARKS_TAGGED_TITLES[Tags.GLADSTONE_GANDER].append((Titles.DUCKBURG_PET_PARADE_THE, []))
BARKS_TAGGED_TITLES[Tags.GLADSTONE_GANDER].append((Titles.HERO_OF_THE_DIKE, []))
BARKS_TAGGED_TITLES[Tags.GLADSTONE_GANDER].append((Titles.DUCK_OUT_OF_LUCK, []))
BARKS_TAGGED_TITLES[Tags.GLADSTONE_GANDER].append((Titles.NOT_SO_ANCIENT_MARINER_THE, []))

BARKS_TAGGED_TITLES[Tags.GYRO_GEARLOOSE].append((Titles.GRANDMAS_PRESENT, []))
BARKS_TAGGED_TITLES[Tags.GYRO_GEARLOOSE].append((Titles.HOBBLIN_GOBLINS, []))
BARKS_TAGGED_TITLES[Tags.GYRO_GEARLOOSE].append((Titles.FORBIDIUM_MONEY_BIN_THE, []))
BARKS_TAGGED_TITLES[Tags.GYRO_GEARLOOSE].append((Titles.AUGUST_ACCIDENT, []))
BARKS_TAGGED_TITLES[Tags.GYRO_GEARLOOSE].append((Titles.WEATHER_WATCHERS_THE, []))
BARKS_TAGGED_TITLES[Tags.GYRO_GEARLOOSE].append((Titles.GAB_MUFFER_THE, []))
BARKS_TAGGED_TITLES[Tags.GYRO_GEARLOOSE].append((Titles.STUBBORN_STORK_THE, []))
BARKS_TAGGED_TITLES[Tags.GYRO_GEARLOOSE].append((Titles.MILKTIME_MELODIES, []))
BARKS_TAGGED_TITLES[Tags.GYRO_GEARLOOSE].append((Titles.LOST_RABBIT_FOOT_THE, []))
BARKS_TAGGED_TITLES[Tags.GYRO_GEARLOOSE].append((Titles.BIRD_CAMERA_THE, []))
BARKS_TAGGED_TITLES[Tags.GYRO_GEARLOOSE].append((Titles.ODD_ORDER_THE, []))
BARKS_TAGGED_TITLES[Tags.GYRO_GEARLOOSE].append((Titles.CALL_OF_THE_WILD_THE, []))
BARKS_TAGGED_TITLES[Tags.GYRO_GEARLOOSE].append((Titles.CAVE_OF_THE_WINDS, []))
BARKS_TAGGED_TITLES[Tags.GYRO_GEARLOOSE].append((Titles.MIXED_UP_MIXER, []))
BARKS_TAGGED_TITLES[Tags.GYRO_GEARLOOSE].append((Titles.MADBALL_PITCHER_THE, []))
BARKS_TAGGED_TITLES[Tags.GYRO_GEARLOOSE].append((Titles.BEAR_TAMER_THE, []))
BARKS_TAGGED_TITLES[Tags.GYRO_GEARLOOSE].append((Titles.TALE_OF_THE_TAPE, []))
BARKS_TAGGED_TITLES[Tags.GYRO_GEARLOOSE].append((Titles.HIS_SHINING_HOUR, []))
BARKS_TAGGED_TITLES[Tags.GYRO_GEARLOOSE].append((Titles.PICNIC, []))
BARKS_TAGGED_TITLES[Tags.GYRO_GEARLOOSE].append((Titles.SEVEN_CITIES_OF_CIBOLA_THE, []))
BARKS_TAGGED_TITLES[Tags.GYRO_GEARLOOSE].append((Titles.HEIRLOOM_WATCH, []))
BARKS_TAGGED_TITLES[Tags.GYRO_GEARLOOSE].append((Titles.TRAPPED_LIGHTNING, []))
BARKS_TAGGED_TITLES[Tags.GYRO_GEARLOOSE].append((Titles.INVENTOR_OF_ANYTHING, []))
BARKS_TAGGED_TITLES[Tags.GYRO_GEARLOOSE].append((Titles.CAT_BOX_THE, []))
BARKS_TAGGED_TITLES[Tags.GYRO_GEARLOOSE].append((Titles.FORECASTING_FOLLIES, []))
BARKS_TAGGED_TITLES[Tags.GYRO_GEARLOOSE].append((Titles.FISHING_MYSTERY, []))
BARKS_TAGGED_TITLES[Tags.GYRO_GEARLOOSE].append((Titles.SURE_FIRE_GOLD_FINDER_THE, []))
BARKS_TAGGED_TITLES[Tags.GYRO_GEARLOOSE].append((Titles.GYRO_BUILDS_A_BETTER_HOUSE, []))
BARKS_TAGGED_TITLES[Tags.GYRO_GEARLOOSE].append((Titles.ROSCOE_THE_ROBOT, []))
BARKS_TAGGED_TITLES[Tags.GYRO_GEARLOOSE].append((Titles.GETTING_THOR, []))
BARKS_TAGGED_TITLES[Tags.GYRO_GEARLOOSE].append((Titles.KNOW_IT_ALL_MACHINE_THE, []))
BARKS_TAGGED_TITLES[Tags.GYRO_GEARLOOSE].append((Titles.GYRO_GOES_FOR_A_DIP, []))
BARKS_TAGGED_TITLES[Tags.GYRO_GEARLOOSE].append((Titles.HOUSE_ON_CYCLONE_HILL_THE, []))
BARKS_TAGGED_TITLES[Tags.GYRO_GEARLOOSE].append((Titles.WISHING_WELL_THE, []))
BARKS_TAGGED_TITLES[Tags.GYRO_GEARLOOSE].append((Titles.KRANKENSTEIN_GYRO, []))
BARKS_TAGGED_TITLES[Tags.GYRO_GEARLOOSE].append((Titles.FIREFLY_TRACKER_THE, []))
BARKS_TAGGED_TITLES[Tags.GYRO_GEARLOOSE].append((Titles.INVENTORS_CONTEST_THE, []))
BARKS_TAGGED_TITLES[Tags.GYRO_GEARLOOSE].append((Titles.OODLES_OF_OOMPH, []))
BARKS_TAGGED_TITLES[Tags.GYRO_GEARLOOSE].append((Titles.WAR_PAINT, []))
BARKS_TAGGED_TITLES[Tags.GYRO_GEARLOOSE].append((Titles.FISHY_WARDEN, []))
BARKS_TAGGED_TITLES[Tags.GYRO_GEARLOOSE].append((Titles.THAT_SMALL_FEELING, []))
BARKS_TAGGED_TITLES[Tags.GYRO_GEARLOOSE].append((Titles.YOU_CANT_WIN, []))
BARKS_TAGGED_TITLES[Tags.GYRO_GEARLOOSE].append((Titles.WILY_RIVAL, []))
BARKS_TAGGED_TITLES[Tags.GYRO_GEARLOOSE].append((Titles.FAST_AWAY_CASTAWAY, []))
BARKS_TAGGED_TITLES[Tags.GYRO_GEARLOOSE].append((Titles.DUCKBURGS_DAY_OF_PERIL, []))
BARKS_TAGGED_TITLES[Tags.GYRO_GEARLOOSE].append((Titles.GREAT_POP_UP_THE, []))
BARKS_TAGGED_TITLES[Tags.GYRO_GEARLOOSE].append((Titles.MADCAP_INVENTORS, []))
BARKS_TAGGED_TITLES[Tags.GYRO_GEARLOOSE].append((Titles.FINNY_FUN, []))
BARKS_TAGGED_TITLES[Tags.GYRO_GEARLOOSE].append((Titles.POSTHASTY_POSTMAN, []))
BARKS_TAGGED_TITLES[Tags.GYRO_GEARLOOSE].append((Titles.SNOW_DUSTER, []))
BARKS_TAGGED_TITLES[Tags.GYRO_GEARLOOSE].append((Titles.HELPERS_HELPING_HAND_A, []))
BARKS_TAGGED_TITLES[Tags.GYRO_GEARLOOSE].append((Titles.MAN_VERSUS_MACHINE, []))
BARKS_TAGGED_TITLES[Tags.GYRO_GEARLOOSE].append((Titles.JONAH_GYRO, []))
BARKS_TAGGED_TITLES[Tags.GYRO_GEARLOOSE].append((Titles.GLADSTONES_TERRIBLE_SECRET, []))
BARKS_TAGGED_TITLES[Tags.GYRO_GEARLOOSE].append((Titles.THINK_BOX_BOLLIX_THE, []))
BARKS_TAGGED_TITLES[Tags.GYRO_GEARLOOSE].append((Titles.TALKING_DOG_THE, []))
BARKS_TAGGED_TITLES[Tags.GYRO_GEARLOOSE].append((Titles.WORM_WEARY, []))
BARKS_TAGGED_TITLES[Tags.GYRO_GEARLOOSE].append((Titles.TOO_SAFE_SAFE, []))
BARKS_TAGGED_TITLES[Tags.GYRO_GEARLOOSE].append((Titles.SMOKE_WRITER_IN_THE_SKY, []))
BARKS_TAGGED_TITLES[Tags.GYRO_GEARLOOSE].append((Titles.GYROS_IMAGINATION_INVENTION, []))
BARKS_TAGGED_TITLES[Tags.GYRO_GEARLOOSE].append((Titles.DAY_DUCKBURG_GOT_DYED_THE, []))
BARKS_TAGGED_TITLES[Tags.GYRO_GEARLOOSE].append((Titles.ROCKET_RACE_AROUND_THE_WORLD, []))
BARKS_TAGGED_TITLES[Tags.GYRO_GEARLOOSE].append((Titles.BLACK_WEDNESDAY, []))
BARKS_TAGGED_TITLES[Tags.GYRO_GEARLOOSE].append((Titles.KNIGHTS_OF_THE_FLYING_SLEDS, []))
BARKS_TAGGED_TITLES[Tags.GYRO_GEARLOOSE].append((Titles.VILLAGE_BLACKSMITH_THE, []))
BARKS_TAGGED_TITLES[Tags.GYRO_GEARLOOSE].append((Titles.BALLOONATICS, []))
BARKS_TAGGED_TITLES[Tags.GYRO_GEARLOOSE].append((Titles.MISSILE_FIZZLE, []))
BARKS_TAGGED_TITLES[Tags.GYRO_GEARLOOSE].append((Titles.MADCAP_MARINER_THE, []))
BARKS_TAGGED_TITLES[Tags.GYRO_GEARLOOSE].append((Titles.STRANGER_THAN_FICTION, []))
BARKS_TAGGED_TITLES[Tags.GYRO_GEARLOOSE].append((Titles.JET_WITCH, []))
BARKS_TAGGED_TITLES[Tags.GYRO_GEARLOOSE].append((Titles.DUCKBURG_PET_PARADE_THE, []))
BARKS_TAGGED_TITLES[Tags.GYRO_GEARLOOSE].append((Titles.CAPN_BLIGHTS_MYSTERY_SHIP, []))
BARKS_TAGGED_TITLES[Tags.GYRO_GEARLOOSE].append((Titles.FUN_WHATS_THAT, []))

BARKS_TAGGED_TITLES[Tags.HERBERT].append((Titles.THREE_DIRTY_LITTLE_DUCKS, []))
BARKS_TAGGED_TITLES[Tags.HERBERT].append((Titles.TEN_CENTS_WORTH_OF_TROUBLE, []))
BARKS_TAGGED_TITLES[Tags.HERBERT].append((Titles.SMUGSNORKLE_SQUATTIE_THE, []))

BARKS_TAGGED_TITLES[Tags.MAGICA_DE_SPELL].append((Titles.MIDAS_TOUCH_THE, []))
BARKS_TAGGED_TITLES[Tags.MAGICA_DE_SPELL].append((Titles.UNSAFE_SAFE_THE, []))
BARKS_TAGGED_TITLES[Tags.MAGICA_DE_SPELL].append((Titles.ODDBALL_ODYSSEY, []))
BARKS_TAGGED_TITLES[Tags.MAGICA_DE_SPELL].append((Titles.FOR_OLD_DIMES_SAKE, []))
BARKS_TAGGED_TITLES[Tags.MAGICA_DE_SPELL].append((Titles.ISLE_OF_GOLDEN_GEESE, []))
BARKS_TAGGED_TITLES[Tags.MAGICA_DE_SPELL].append((Titles.MANY_FACES_OF_MAGICA_DE_SPELL_THE, []))
BARKS_TAGGED_TITLES[Tags.MAGICA_DE_SPELL].append((Titles.RUG_RIDERS_IN_THE_SKY, []))
BARKS_TAGGED_TITLES[Tags.MAGICA_DE_SPELL].append((Titles.TEN_CENT_VALENTINE, []))
BARKS_TAGGED_TITLES[Tags.MAGICA_DE_SPELL].append((Titles.RAVEN_MAD, []))

BARKS_TAGGED_TITLES[Tags.NEIGHBOR_JONES].append((Titles.GOOD_DEEDS, []))
BARKS_TAGGED_TITLES[Tags.NEIGHBOR_JONES].append((Titles.GOOD_NEIGHBORS, []))
BARKS_TAGGED_TITLES[Tags.NEIGHBOR_JONES].append((Titles.PURLOINED_PUTTY_THE, []))
BARKS_TAGGED_TITLES[Tags.NEIGHBOR_JONES].append((Titles.TEN_DOLLAR_DITHER, []))
BARKS_TAGGED_TITLES[Tags.NEIGHBOR_JONES].append((Titles.SILENT_NIGHT, []))
BARKS_TAGGED_TITLES[Tags.NEIGHBOR_JONES].append((Titles.GOOD_DEEDS_THE, []))
BARKS_TAGGED_TITLES[Tags.NEIGHBOR_JONES].append((Titles.FEUD_AND_FAR_BETWEEN, []))
BARKS_TAGGED_TITLES[Tags.NEIGHBOR_JONES].append((Titles.UNFRIENDLY_ENEMIES, []))


def get_tagged_titles(tag: Tags) -> List[Titles]:
    """
    Retrieves a sorted list of unique titles associated with a specific tag.
    """
    return sorted([t[0] for t in BARKS_TAGGED_TITLES[tag]])


def get_tag_categories_titles() -> Dict[TagCategories, List[Titles]]:
    """
    Gets a dictionary mapping each TagCategory to a sorted list of unique titles
    associated with the tags/groups in that category.
    """
    tag_categories_titles = {}

    for category in TagCategories:
        tag_categories_titles[category] = __get_tag_titles(BARKS_TAG_CATEGORIES[category])

    return tag_categories_titles


def get_tag_group_titles() -> Dict[TagGroups, List[Titles]]:
    """
    Gets a dictionary mapping each TagGroup to a sorted list of unique titles
    associated with the tags in that group.
    """
    tag_group_titles = {}

    for tag_group in TagGroups:
        tag_group_titles[tag_group] = __get_tag_titles(BARKS_TAG_GROUPS[tag_group])

    return tag_group_titles


def __get_tag_titles(tag_list: List[Tags]) -> List[Titles]:
    title_list = []
    for tag in tag_list:
        title_list.extend([t[0] for t in BARKS_TAGGED_TITLES[tag]])

    return sorted(list(set(title_list)))


BARKS_TAG_CATEGORIES_TITLES: Dict[TagCategories, List[Titles]] = get_tag_categories_titles()
BARKS_TAG_GROUPS_TITLES: Dict[TagGroups, List[Titles]] = get_tag_group_titles()
